baseURL = 'https://theworldmessage.com/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'minimal'

[params]
  description = 'A minimalist blog'

[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.highlight]
    style = 'monokailight'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
