baseURL = 'https://blog.theworldmessage.com/'
languageCode = 'en-us'
title = 'writing just for the sake of it'
theme = 'minimal'

[params]
  twitter = "https://x.com/cigsandcoffe3"


[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.highlight]
    style = 'monokailight'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
