baseURL = 'https://blog.theworldmessage.com/'
languageCode = 'en-us'
title = 'A place for me to write things'
theme = 'minimal'

[params]


[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.highlight]
    style = 'monokailight'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
